server:
  port: 10100

logging:
  level:
    root: INFO

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: identity-service
          uri: http://localhost:10110
          metadata:
            healthcheck: /actuator/health
          predicates:
            - Path=/identity/**
        - id: student-service
          uri: http://localhost:10120
          metadata:
            healthcheck: /actuator/health
          predicates:
            - Path=/students/**
        - id: course-service
          uri: http://localhost:10130
          metadata:
            healthcheck: /actuator/health
          predicates:
            - Path=/courses/**

security:
  jwt:
    token:
      secret-key: zdtlD3JK56m6wTTgsNFhqzjqP

